name: tiki_app_testing
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  get_it: ^3.0.0+1
  http: ^0.12.0+2
  url_launcher: ^5.1.2
  flutter_spinkit: "^4.0.0"
  bloc: ^0.15.0
  flutter_bloc: ^0.21.0
  equatable: ^0.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
